routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('guest');

Auth::routes();

Route::get('user/profile', 'HomeController@profile')->name('user.profile');

Route::patch('user/update', 'HomeController@update')->name('user.update');

Route::get('register/bank', 'Auth\BankRegisterController@showBankRegistration')->name('register.bank');

Route::post('register/bank', 'Auth\BankRegisterController@register')->name('register.bank');

Route::get('register/agent', 'Auth\AgentRegisterController@showRegistrationForm')->name('register.agent')->middleware('hasInvitation');

Route::post('register/agent', 'Auth\AgentRegisterController@register')->name('register.agent');

Route::get('register/advisor', 'Auth\AdvisorRegisterController@showRegistrationForm')->name('register.advisor')->middleware('hasInvitation');

Route::post('register/advisor', 'Auth\AdvisorRegisterController@register')->name('register.advisor');


Route::get('register/user', 'Auth\UserRegisterController@showRegistrationForm')->name('register.user')->middleware('hasInvitation');

Route::post('register/user', 'Auth\UserRegisterController@register')->name('register.user');


Route::get('/home', 'HomeController@index')->name('home');

Route::resource('loan_application', 'LoanApplicationController');



Route::get('bank', 'BankController@index')->name('bank.index');

Route::group(['middleware' => ['role:bank', 'permission:create packages|edit packages|delete packages']], function() {

    Route::get('packages', 'PackagesController@index')->name('packages.index');

    Route::post('packages', 'PackagesController@store')->name('packages.store');

    Route::get('packages/{packages}/edit', 'PackagesController@edit')->name('packages.edit');

    Route::patch('packages/{packages}', 'PackagesController@update')->name('packages.update');

    Route::delete('packages/{packages}', 'PackagesController@destroy')->name('packages.destroy');

});





Route::post('bank/{loan_application}/{package}', 'LoanApplicationController@accept')->name('bank.accept');

Route::get('loan_applications', 'UsersApplicationController@show')->name('loan_applications');

Route::get('loan_applications/logs', 'UsersApplicationController@logs')->name('user.logs');

Route::get('loan_applications/offers/{loan_application}', 'UsersApplicationController@show_offers')->name('show_loan_offers');

Route::get('bank/user_applications', 'BankController@user_applications')->name('user_applications.fetch');

Route::get('bank/logs', 'BankController@logs')->name('bank.logs');

Route::get('bank/agents', 'AgentController@index')->name('bank.agents');

Route::post('loan_applications/offers/declined/{bank_verdict}', 'UsersApplicationController@destroy')->name('offer_rejected');


Route::group(['middleware' => ['role:admin']], function() {

  Route::get('admin', 'AdminController@index')->name('admin.index');

  Route::get('admin/banks', 'AdminController@bank')->name('admin.banks');

  Route::patch('admin/banks/approve/{user}', 'AdminController@bank_approve')->name('admin.bank.approve');

  Route::patch('admin/banks/disable/{user}', 'AdminController@bank_disable')->name('admin.bank.disable');

  Route::get('admin/users', 'AdminController@users')->name('admin.users');
});

Route::group(['middleware' => ['permission:send messages|video chat']], function() {
  Route::get('chat/book', 'ChatController@book')->name('chat.book');
  Route::get('/chat/home', 'ChatController@index')->name('chat.home');
  Route::get('/chat/{id}', 'ChatController@chat')->name('chat');
  Route::get('/group/chat/{id}', 'ChatController@groupChat')->name('group.chat');

  Route::post('/chat/message/send', 'ChatController@send')->name('chat.send');
  Route::post('/chat/message/send/file', 'ChatController@sendFilesInConversation')->name('chat.send.file');
  Route::post('/group/chat/message/send', 'ChatController@groupSend')->name('group.send');
  Route::post('/group/chat/message/send/file', 'ChatController@sendFilesInGroupConversation')->name('group.send.file');

  Route::get('/accept/message/request/{id}' , function ($id){
      Chat::acceptMessageRequest($id);
      return redirect()->back();
  })->name('accept.message');

  Route::post('/trigger/{id}' , function (\Illuminate\Http\Request $request , $id) {
      Chat::startVideoCall($id , $request->all());
  });

  Route::post('/group/chat/leave/{id}' , function ($id) {
      Chat::leaveFromGroupConversation($id);
  });

});

Route::group(['middleware' => ['role:bank', 'permission:check agent activity']], function() {
  Route::resource('bank/agent', 'AgentController');
});

Route::get('bank/link', 'AgentController@sendInvitation')->name('send.invitation');

Route::get('bank/advisor/link', 'AdvisorController@sendInvitation')->name('send.advisor.invitation');

Route::group(['middleware' => ['auth', 'role:bank'], 'prefix' => 'invitations'], function() {

  Route::get('/' , 'InvitationsController@index')->name('showInvitations');

  Route::post('/agent', 'InvitationsController@store')->name('storeInvitation');

  Route::get('/advisor' , 'AdvisorController@invites')->name('showAdvisorInvitations');

  Route::post('/advisor', 'AdvisorController@store')->name('storeAdvisorInvitation');

});

Route::group(['middleware' => ['auth', 'role:bank']], function() {
  Route::post('/agent/disable/{user}' , 'AgentController@agent_disable')->name('disable_agent');

  Route::post('/agent/enable/{user}' , 'AgentController@agent_enable')->name('enable_agent');

  Route::get('/advisors', 'AdvisorController@index')->name('advisors.index');
});

Route::post('/loan/application', 'HomePageController@store')->name('store.loan');

app/Agent.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Agent extends Model
{
    protected $fillable = [
      'user_id', 'invite_id', 'created_at', 'updated_at'
    ];


    
}

app/Http/Controllers/AgentController.php
<?php

namespace App\Http\Controllers;

use App\Agent;
use App\User;
use Illuminate\Http\Request;
use Session;

class AgentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $agents = User::role('agent')
                    ->withTrashed()
                    ->get();

      return view('bank.agent.index', compact('agents'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('bank.agent.create');
    }

    public function agent_disable($user) {
      User::find($user)->delete();

      Session::flash('agent_disable', 'Agent disabled successfully');

      return redirect()->route('bank.agents');
    }

    public function agent_enable($user) {
      User::find($user)->restore();

      Session::flash('agent_enabled', 'Agent enabled successfully');

      return redirect()->route('bank.agents');
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Agent  $agent
     * @return \Illuminate\Http\Response
     */
    public function show(Agent $agent)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Agent  $agent
     * @return \Illuminate\Http\Response
     */
    public function edit(Agent $agent)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Agent  $agent
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Agent $agent)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Agent  $agent
     * @return \Illuminate\Http\Response
     */
    public function destroy(Agent $agent)
    {
        //
    }

    public function sendInvitation() {
      return view('bank.agent.link');
    }
}

app/Http/Controllers/BankController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Builder;
use App\LoanApplication;
use App\User;
use App\BankVerdict;
use App\Invitation;
use App\Agent;
use DB;

class BankController extends Controller
{
  public function index()
  {
      // $loans =DB::table('loan_application')->latest()->take(5)->get();
      return view('bank.index');
  }

  public function user_applications() {
    $login_user = \Auth::user();

    if ($login_user->hasRole('bank')) {
      $user_loans = LoanApplication::whereDoesntHave('bank_verdict', function (Builder $query) {
          $query->where('bank_id', 'like', \Auth::user()->id);
      })->get();
    }

    elseif ($login_user->hasRole('agent')) {
      // $agent = Agent::where('user_id', 'like' ,\Auth::user()->id);
      //
      // $invitation = Invitation::where('id', 'like', $agent->invite_id)->first();

      // $agent = Agent::with('invite_by')->where('user_id', \Auth::user()->id)->first();
      // $invitation = $agent->invite_by->toArray();
      //



      $user_loans = LoanApplication::whereDoesntHave('bank_verdict', function (Builder $query) {
          $query->where('bank_id', 'like', Invitation::whereHas('invite_for', function(Builder $query) {
            $query->where('user_id', 'like', \Auth::user()->id);
          })->get('bank_id'));
      })->get();
    }


    return view('bank.loan_applications', compact('user_loans'));
  }

  public function logs() {
    $logs = LoanApplication::whereHas('bank_verdict', function(Builder $query) {
      $query->where('bank_id', 'like', \Auth::user()->id);
    })->get();

    return view('bank.logs', compact('logs'));
  }

}

resources/views/bank/agent/create.blade.php
@extends('layouts.bank_layout')

@section('content')
  @role('bank')
    <div class="container">
    <form method="POST" action="{{ route('agent.store') }}">
      {{ csrf_field() }}
      <div class="form-group">
        <label for="title">Name</label>
        <input type="text" name="title" class="form-control" id="exampleInputEmail1" value="{{ old('email') }}" aria-describedby="emailHelp" placeholder="Enter Title">
      </div>
      <div class="form-group">
        <label for="interest">Interest</label>
        <input type="number" name="interest" class="form-control" value="{{ $my_package->interest }}" placeholder="Enter Interest">
      </div>
      <div class="duration">
        <label for="duration">Duration</label>
        <input type="number" name="duration" value="{{ $my_package->duration }}" class="form-control {{ $errors->has('duration') ? 'is-danger' : '' }}" placeholder="Enter Duration">
      </div>

      <button type="submit" class="btn btn-primary">Create Agent</button>
    </form>

    @include('errors')

    <form action="{{ route('packages.destroy', ['packages' => $my_package->id]) }}" method="post">
      {{ method_field('DELETE') }}
      <button type="submit" class="btn btn-warning">Delete Package</button>
    </form>
  </div>

  @else
    <div class="col-md-8">
        <div class="panel panel-default">
            {{-- <div class="panel-heading">Dashboard</div> --}}

            <div class="panel-body">
                <div class="alert alert-warning">
                    Warning
                </div>
                You do not have the appropriate permissions to access this page
            </div>
        </div>
    </div>
  @endrole
@endsection

resources/views/bank/agent/index.blade.php
@extends('layouts.bank_layout')

@section('css')
<style>
  body {
        color: #566787;
        background: #f5f5f5;
		font-family: 'Roboto', sans-serif;
	}
	.table-wrapper {
        background: #fff;
        padding: 20px;
        margin: 30px 0;
        box-shadow: 0 1px 1px rgba(0,0,0,.05);
    }
	.table-title {
        padding-bottom: 10px;
        margin: 0 0 10px;
    }
    .table-title h2 {
        margin: 8px 0 0;
        font-size: 22px;
    }
    .search-box {
        position: relative;
        float: right;
    }
    .search-box input {
        height: 34px;
        border-radius: 20px;
        padding-left: 35px;
        border-color: #ddd;
        box-shadow: none;
    }
	.search-box input:focus {
		border-color: #3FBAE4;
	}
    .search-box i {
        color: #a0a5b1;
        position: absolute;
        font-size: 19px;
        top: 8px;
        left: 10px;
    }
    table.table tr th, table.table tr td {
        border-color: #e9e9e9;
    }
    table.table-striped tbody tr:nth-of-type(odd) {
    	background-color: #fcfcfc;
	}
	table.table-striped.table-hover tbody tr:hover {
		background: #f5f5f5;
	}
    table.table th i {
        font-size: 13px;
        margin: 0 5px;
        cursor: pointer;
    }
    table.table td:last-child {
        width: 130px;
    }
    table.table td a {
        color: #a0a5b1;
        display: inline-block;
        margin: 0 5px;
    }
	table.table td a.view {
        color: #03A9F4;
    }
    table.table td a.edit {
        color: #FFC107;
    }
    table.table td a.delete {
        color: #E34724;
    }
    table.table td i {
        font-size: 19px;
    }
    .pagination {
        float: right;
        margin: 0 0 5px;
    }
    .pagination li a {
        border: none;
        font-size: 95%;
        width: 30px;
        height: 30px;
        color: #999;
        margin: 0 2px;
        line-height: 30px;
        border-radius: 30px !important;
        text-align: center;
        padding: 0;
    }
    .pagination li a:hover {
        color: #666;
    }
    .pagination li.active a {
        background: #03A9F4;
    }
    .pagination li.active a:hover {
        background: #0397d6;
    }
	.pagination li.disabled i {
        color: #ccc;
    }
    .pagination li i {
        font-size: 16px;
        padding-top: 6px
    }
    .hint-text {
        float: left;
        margin-top: 6px;
        font-size: 95%;
    }
</style>
@endsection


@section('content')
  <a href="{{ route('showInvitations') }}" class="btn btn-info">Pending Requests</a><br />
  <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-8"><h2> {{ Auth::user()->name }}<b>Agents</b></h2></div>
                    <div class="col-sm-4">
                        <div class="search-box">
                            <i class="material-icons">&#xE8B6;</i>
                            <input type="text" class="form-control" placeholder="Search&hellip;">
                        </div>
                    </div>
                </div>
            </div>
            @if (!empty($agents))
            <table class="table table-striped table-hover table-bordered">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Name <i class="fa fa-sort"></i></th>
                        <th>Email</th>
                        <th>Phone Number <i class="fa fa-sort"></i></th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                  @foreach ($agents as $agent)
                    <tr>
                      <tr>
                        <td>
                          {{ $agent->id }}
                        </td>
                        <td>
                          {{ $agent->name }}
                        </td>
                        <td>
                          {{ $agent->email }}
                        </td>
                        <td>
                          {{ $agent->phone_number }}
                        </td>
                        <td>
                            @if ($agent->deleted_at != null)
                              <form action="{{ route('enable_agent', ['user' => $agent->id]) }}" method="post">
                                {{ csrf_field() }}
                                <button href="#" class="view" title="Re-activate" data-toggle="tooltip"><i class="material-icons">&#xE417;</i></button>
                              </form>

                            @endif
                            <a href="#" class="edit" title="Edit" data-toggle="tooltip"><i class="material-icons">&#xE254;</i></a>
                            @if ($agent->deleted_at == null)
                              <form action="{{ route('disable_agent', ['user' => $agent->id]) }}" method="POST">
                                {{ csrf_field() }}
                                  <button href="" class="btn btn-warning" title="Disable" data-toggle="tooltip"><i class="material-icons">&#xE872;</i></button>
                              </form>

                            @endif

                        </td>
                    </tr>
                  @endforeach
                </tbody>
            </table>
          @else
            <p>No Agents Yet</p>
          @endif
        </div>
      </div>
@endsection

resources/views/bank/agent/invitations.blade.php
@extends('layouts.bank_layout')

@section('css')
<style>
  body {
        color: #566787;
        background: #f5f5f5;
		font-family: 'Roboto', sans-serif;
	}
	.table-wrapper {
        background: #fff;
        padding: 20px;
        margin: 30px 0;
        box-shadow: 0 1px 1px rgba(0,0,0,.05);
    }
	.table-title {
        padding-bottom: 10px;
        margin: 0 0 10px;
    }
    .table-title h2 {
        margin: 8px 0 0;
        font-size: 22px;
    }
    .search-box {
        position: relative;
        float: right;
    }
    .search-box input {
        height: 34px;
        border-radius: 20px;
        padding-left: 35px;
        border-color: #ddd;
        box-shadow: none;
    }
	.search-box input:focus {
		border-color: #3FBAE4;
	}
    .search-box i {
        color: #a0a5b1;
        position: absolute;
        font-size: 19px;
        top: 8px;
        left: 10px;
    }
    table.table tr th, table.table tr td {
        border-color: #e9e9e9;
    }
    table.table-striped tbody tr:nth-of-type(odd) {
    	background-color: #fcfcfc;
	}
	table.table-striped.table-hover tbody tr:hover {
		background: #f5f5f5;
	}
    table.table th i {
        font-size: 13px;
        margin: 0 5px;
        cursor: pointer;
    }
    table.table td:last-child {
        width: 130px;
    }
    table.table td a {
        color: #a0a5b1;
        display: inline-block;
        margin: 0 5px;
    }
	table.table td a.view {
        color: #03A9F4;
    }
    table.table td a.edit {
        color: #FFC107;
    }
    table.table td a.delete {
        color: #E34724;
    }
    table.table td i {
        font-size: 19px;
    }
    .pagination {
        float: right;
        margin: 0 0 5px;
    }
    .pagination li a {
        border: none;
        font-size: 95%;
        width: 30px;
        height: 30px;
        color: #999;
        margin: 0 2px;
        line-height: 30px;
        border-radius: 30px !important;
        text-align: center;
        padding: 0;
    }
    .pagination li a:hover {
        color: #666;
    }
    .pagination li.active a {
        background: #03A9F4;
    }
    .pagination li.active a:hover {
        background: #0397d6;
    }
	.pagination li.disabled i {
        color: #ccc;
    }
    .pagination li i {
        font-size: 16px;
        padding-top: 6px
    }
    .hint-text {
        float: left;
        margin-top: 6px;
        font-size: 95%;
    }
</style>
@endsection

@section('content')
  <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-8"><h2>Pending <b>Requests</b></h2></div>
                    <div class="col-sm-4">
                        <div class="search-box">
                            <i class="material-icons">&#xE8B6;</i>
                            <input type="text" class="form-control" placeholder="Search&hellip;">
                        </div>
                    </div>
                </div>
            </div>
            @if (!empty($invitations))
            <table class="table table-striped table-hover table-bordered">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Email <i class="fa fa-sort"></i></th>
                        <th>Created At</th>
                        <th>Invitation Link <i class="fa fa-sort"></i></th>
                    </tr>
                </thead>
                <tbody>
                  @foreach ($invitations as $invitation)
                    <tr>
                      <td>{{ $invitation->id }}</td>
                      <td><a href="mailto:{{ $invitation->email }}">{{ $invitation->email }}</a></td>
                      <td>{{ $invitation->created_at }}</td>
                      <td>
                        <kbd>{{ $invitation->getLink() }}</kbd>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
            </table>
          @else
            <p>No Invitation Requests!!</p>
          @endif
        </div>
      </div>
  <div class="container">
    <div class="page-header" style="margin-top: 0">
      <h1>Sent Invitations</h1>
    </div>


@endsection

resources/views/bank/agent/link.blade.php
@extends('layouts.bank_layout')

@section('content')
  @role('bank')
    <div class="container">
    <form method="POST" action="{{ route('storeInvitation') }}">
      {{ csrf_field() }}
      <div class="form-group">
        <label for="title">Email</label>
        <input type="text" name="email" class="form-control" id="exampleInputEmail1" value="{{ old('email') }}" placeholder="Enter Email">
      </div>

      <button type="submit" class="btn btn-primary">Create Agent</button>
    </form>

    @include('errors')
  @else
    <div class="col-md-8">
        <div class="panel panel-default">
            {{-- <div class="panel-heading">Dashboard</div> --}}

            <div class="panel-body">
                <div class="alert alert-warning">
                    Warning
                </div>
                You do not have the appropriate permissions to access this page
            </div>
        </div>
    </div>
  @endrole
@endsection