routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->middleware('guest');

Auth::routes();

Route::get('user/profile', 'HomeController@profile')->name('user.profile');

Route::patch('user/update', 'HomeController@update')->name('user.update');

Route::get('register/bank', 'Auth\BankRegisterController@showBankRegistration')->name('register.bank');

Route::post('register/bank', 'Auth\BankRegisterController@register')->name('register.bank');

Route::get('register/agent', 'Auth\AgentRegisterController@showRegistrationForm')->name('register.agent')->middleware('hasInvitation');

Route::post('register/agent', 'Auth\AgentRegisterController@register')->name('register.agent');

Route::get('register/advisor', 'Auth\AdvisorRegisterController@showRegistrationForm')->name('register.advisor')->middleware('hasInvitation');

Route::post('register/advisor', 'Auth\AdvisorRegisterController@register')->name('register.advisor');


Route::get('register/user', 'Auth\UserRegisterController@showRegistrationForm')->name('register.user')->middleware('hasInvitation');

Route::post('register/user', 'Auth\UserRegisterController@register')->name('register.user');


Route::get('/home', 'HomeController@index')->name('home');

Route::resource('loan_application', 'LoanApplicationController');



Route::get('bank', 'BankController@index')->name('bank.index');

Route::group(['middleware' => ['role:bank', 'permission:create packages|edit packages|delete packages']], function() {

    Route::get('packages', 'PackagesController@index')->name('packages.index');

    Route::post('packages', 'PackagesController@store')->name('packages.store');

    Route::get('packages/{packages}/edit', 'PackagesController@edit')->name('packages.edit');

    Route::patch('packages/{packages}', 'PackagesController@update')->name('packages.update');

    Route::delete('packages/{packages}', 'PackagesController@destroy')->name('packages.destroy');

});





Route::post('bank/{loan_application}/{package}', 'LoanApplicationController@accept')->name('bank.accept');

Route::get('loan_applications', 'UsersApplicationController@show')->name('loan_applications');

Route::get('loan_applications/logs', 'UsersApplicationController@logs')->name('user.logs');

Route::get('loan_applications/offers/{loan_application}', 'UsersApplicationController@show_offers')->name('show_loan_offers');

Route::get('bank/user_applications', 'BankController@user_applications')->name('user_applications.fetch');

Route::get('bank/logs', 'BankController@logs')->name('bank.logs');

Route::get('bank/agents', 'AgentController@index')->name('bank.agents');

Route::post('loan_applications/offers/declined/{bank_verdict}', 'UsersApplicationController@destroy')->name('offer_rejected');


Route::group(['middleware' => ['role:admin']], function() {

  Route::get('admin', 'AdminController@index')->name('admin.index');

  Route::get('admin/banks', 'AdminController@bank')->name('admin.banks');

  Route::patch('admin/banks/approve/{user}', 'AdminController@bank_approve')->name('admin.bank.approve');

  Route::patch('admin/banks/disable/{user}', 'AdminController@bank_disable')->name('admin.bank.disable');

  Route::get('admin/users', 'AdminController@users')->name('admin.users');
});

Route::group(['middleware' => ['permission:send messages|video chat']], function() {
  Route::get('chat/book', 'ChatController@book')->name('chat.book');
  Route::get('/chat/home', 'ChatController@index')->name('chat.home');
  Route::get('/chat/{id}', 'ChatController@chat')->name('chat');
  Route::get('/group/chat/{id}', 'ChatController@groupChat')->name('group.chat');

  Route::post('/chat/message/send', 'ChatController@send')->name('chat.send');
  Route::post('/chat/message/send/file', 'ChatController@sendFilesInConversation')->name('chat.send.file');
  Route::post('/group/chat/message/send', 'ChatController@groupSend')->name('group.send');
  Route::post('/group/chat/message/send/file', 'ChatController@sendFilesInGroupConversation')->name('group.send.file');

  Route::get('/accept/message/request/{id}' , function ($id){
      Chat::acceptMessageRequest($id);
      return redirect()->back();
  })->name('accept.message');

  Route::post('/trigger/{id}' , function (\Illuminate\Http\Request $request , $id) {
      Chat::startVideoCall($id , $request->all());
  });

  Route::post('/group/chat/leave/{id}' , function ($id) {
      Chat::leaveFromGroupConversation($id);
  });

});

Route::group(['middleware' => ['role:bank', 'permission:check agent activity']], function() {
  Route::resource('bank/agent', 'AgentController');
});

Route::get('bank/link', 'AgentController@sendInvitation')->name('send.invitation');

Route::get('bank/advisor/link', 'AdvisorController@sendInvitation')->name('send.advisor.invitation');

Route::group(['middleware' => ['auth', 'role:bank'], 'prefix' => 'invitations'], function() {

  Route::get('/' , 'InvitationsController@index')->name('showInvitations');

  Route::post('/agent', 'InvitationsController@store')->name('storeInvitation');

  Route::get('/advisor' , 'AdvisorController@invites')->name('showAdvisorInvitations');

  Route::post('/advisor', 'AdvisorController@store')->name('storeAdvisorInvitation');

});

Route::group(['middleware' => ['auth', 'role:bank']], function() {
  Route::post('/agent/disable/{user}' , 'AgentController@agent_disable')->name('disable_agent');

  Route::post('/agent/enable/{user}' , 'AgentController@agent_enable')->name('enable_agent');

  Route::get('/advisors', 'AdvisorController@index')->name('advisors.index');
});

Route::post('/loan/application', 'HomePageController@store')->name('store.loan');

app/Http/Controllers/BankController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Builder;
use App\LoanApplication;
use App\User;
use App\BankVerdict;
use App\Invitation;
use App\Agent;
use DB;

class BankController extends Controller
{
  public function index()
  {
      // $loans =DB::table('loan_application')->latest()->take(5)->get();
      return view('bank.index');
  }

  public function user_applications() {
    $login_user = \Auth::user();

    if ($login_user->hasRole('bank')) {
      $user_loans = LoanApplication::whereDoesntHave('bank_verdict', function (Builder $query) {
          $query->where('bank_id', 'like', \Auth::user()->id);
      })->get();
    }

    elseif ($login_user->hasRole('agent')) {
      // $agent = Agent::where('user_id', 'like' ,\Auth::user()->id);
      //
      // $invitation = Invitation::where('id', 'like', $agent->invite_id)->first();

      // $agent = Agent::with('invite_by')->where('user_id', \Auth::user()->id)->first();
      // $invitation = $agent->invite_by->toArray();
      //



      $user_loans = LoanApplication::whereDoesntHave('bank_verdict', function (Builder $query) {
          $query->where('bank_id', 'like', Invitation::whereHas('invite_for', function(Builder $query) {
            $query->where('user_id', 'like', \Auth::user()->id);
          })->get('bank_id'));
      })->get();
    }


    return view('bank.loan_applications', compact('user_loans'));
  }

  public function logs() {
    $logs = LoanApplication::whereHas('bank_verdict', function(Builder $query) {
      $query->where('bank_id', 'like', \Auth::user()->id);
    })->get();

    return view('bank.logs', compact('logs'));
  }

}

resources/views/bank/chat.blade.php
@extends('layouts.bank_layout')

@section('content')
  @can ('send messages')
    @include('chat.chat')
  @endcan

@endsection

resources/views/bank/create_package.blade.php
@extends('layouts.bank_layout')

@section('content')
  @role('bank')
  <center><title>Create {{ Auth::user()->name }} Package</title></center>
    <div class="container">
      <form method="POST" action="{{ route('packages.store') }}">
        {{ csrf_field() }}
        <div class="form-group">
          <label for="title">Title</label>
          <input type="text" name="title" class="form-control" id="exampleInputEmail1" value="{{ old('title') }}" aria-describedby="emailHelp" placeholder="Enter Title">
        </div>
        <div class="form-group">
          <label for="interest">Interest</label>
          <input type="number" name="interest" class="form-control" value="{{ old('interest') }}" placeholder="Enter Interest">
        </div>
        <div class="duration">
          <label for="duration">Duration</label>
          <input type="number" name="duration" value="{{ old('duration') }}" class="form-control {{ $errors->has('duration') ? 'is-danger' : '' }}" placeholder="Enter Duration">
        </div>
        <div class="form-group">
          <label for="terms_and_conditions">Terms and conditions</label>
          <input type="file" name="file" class="form-control-file" id="exampleFormControlFile1">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>

      @include('errors')
    </div>
  @else
    <div class="col-md-8">
        <div class="panel panel-default">
            {{-- <div class="panel-heading">Dashboard</div> --}}

            <div class="panel-body">
                <div class="alert alert-warning">
                    Warning
                </div>
                You do not have the appropriate permissions to access this page
            </div>
        </div>
    </div>
  @endrole
@endsection

resources/views/bank/edit_package.blade.php
@extends('layouts.bank_layout')

@section('content')
  @role('bank')
    <div class="container">
    <form method="POST" action="{{ route('packages.update', ['packages' => $my_package->id]) }}">
      {{ csrf_field() }}
      {{ method_field('PATCH') }}
      <input type="hidden" name="bank_id" value="{{ \Auth::user()->id }}">
      <div class="form-group">
        <label for="title">Title</label>
        <input type="text" name="title" class="form-control" id="exampleInputEmail1" value="{{ $my_package->title }}" aria-describedby="emailHelp" placeholder="Enter Title">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
      </div>
      <div class="form-group">
        <label for="interest">Interest</label>
        <input type="number" name="interest" class="form-control" value="{{ $my_package->interest }}" placeholder="Enter Interest">
      </div>
      <div class="duration">
        <label for="duration">Duration</label>
        <input type="number" name="duration" value="{{ $my_package->duration }}" class="form-control {{ $errors->has('duration') ? 'is-danger' : '' }}" placeholder="Enter Duration">
      </div>
      <div class="form-group">
        <label for="terms_and_conditions">Terms and conditions</label>
        <input type="file" name="terms_and_conditions" class="form-control-file" id="exampleFormControlFile1">
      </div>
      <button type="submit" class="btn btn-primary">Update Package</button>
    </form>

    @include('errors')

    <form action="{{ route('packages.destroy', ['packages' => $my_package->id]) }}" method="post">
      {{ method_field('DELETE') }}
      <button type="submit" class="btn btn-warning">Delete Package</button>
    </form>
  </div>

  @else
    <div class="col-md-8">
        <div class="panel panel-default">
            {{-- <div class="panel-heading">Dashboard</div> --}}

            <div class="panel-body">
                <div class="alert alert-warning">
                    Warning
                </div>
                You do not have the appropriate permissions to access this page
            </div>
        </div>
    </div>
  @endrole
@endsection

resources/views/bank/index.blade.php
@extends('layouts.bank_layout')

@section('content')
  <div class="row">
    <div class="col-md-7 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <div class="clearfix">
            <h4 class="card-title float-left">Visit And Sales Statistics</h4>
            <div id="visit-sale-chart-legend" class="rounded-legend legend-horizontal legend-top-right float-right"></div>
          </div>
          <canvas id="line-canvas" class="mt-4"></canvas>
        </div>
      </div>
    </div>
    <div class="col-md-5 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Traffic Sources</h4>
          <canvas id="traffic-chart"></canvas>
          <div id="traffic-chart-legend" class="rounded-legend legend-vertical legend-bottom-left pt-4"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-12 grid-margin">
      <div class="card">
        <div class="card-body">
          <h4 class="card-title">Recently Applied Loans</h4>
          {{-- <div class="table-responsive">
            <table class="table">

              <!--Table head-->
              <thead>
                <tr>
                  <th>
                    <a>Name
                      <i class="fas fa-sort ml-1"></i>
                    </a>
                  </th>
                  <th>
                    <a>ID Number

                    </a>
                  </th>
                  <th>
                    <a>Phone Number
                      <i class="fas fa-sort ml-1"></i>
                    </a>
                  </th>
                  <th>
                    <a>Amount To Be Loaned
                      <i class="fas fa-sort ml-1"></i>
                    </a>
                  </th>
                  <th>
                    <a>Duration
                      <i class="fas fa-sort ml-1"></i>
                    </a>
                  </th>
                  <th>
                    <a>Logged at
                      <i class="fas fa-sort ml-1"></i>
                    </a>
                  </th>
                </tr>
              </thead>
              <!--Table head-->

              <!--Table body-->
              <tbody>
                <tr>
                  @foreach($loans as $loan)


                  <tr>
                    <td>{{ $loan->users->name }}</td>
                    <td>{{ $loan->users->id_number }}</td>
                    <td>{{ $loan->users->phone_number }}</td>
                    <td>Ksh {{ $loan->loan_value }}</td>
                    <td>{{ $loan->duration }} months</td>
                    {{-- @if($loan->accepted())
                      <td><label class="badge badge-gradient-success">ACCEPTED</label></td>
                    @elseif ($loan->rejected())
                      <td><label class="badge badge-gradient-danger">REJECTED</label></td>
                    @else
                      <td><label class="badge badge-gradient-warning">WATING</label></td>
                    @endif 
                    <td>{{ $loan->created_at }}</td>
                  </tr>


                  @endforeach
                </tr>
              </tbody>
              <!--Table body-->
            </table>

          </div> --}}
        </div>
      </div>
    </div>
  </div>

@endsection

{{-- @extends('layouts.bank_layout')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in as a Bank!
                </div>
            </div>
          </div>
        </div>
      </div>

      @foreach ($user_loans as $user_loan)
        <div class="">
          <li>{{ $user_loan->loan_value }}</li>
          <a href="{{ route('loan_application.show' , ['loan_application' => $user_loan->id ]) }}" class="btn btn-primary">Accept</a>
          <form action="{{ route('loan_application.destroy', [ 'loan_application' => $user_loan->id ]) }}" method="POST">
              {{ method_field('DELETE') }}
              {{ csrf_field() }}
              <button type="submit" class="btn btn-danger">Decline</button>
          </form>

        </div>

      @endforeach



@endsection --}}

resources/views/bank/loan_applications.blade.php
@extends('layouts.bank_layout')

@section('content')

@if ($user_loans->count() == 0)
  <div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title">
          Loan Applications
        </h3>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">

          </ol>
        </nav>
      </div>
      <div class="row">
          <div class="col-md-6 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title text-warning">No new Loan Applications</h4>
                <p class="card-description text-info">
                  Currently, there are no new loan applications.
                </p>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
@endif

@foreach ($user_loans as $user_loan)
  @can ('approve loans')
    <div class="main-panel">
    <div class="content-wrapper">
      <div class="page-header">
        <h3 class="page-title">
          Loan Applications
        </h3>
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">


          </ol>
        </nav>
      </div>
      <div class="row">
          <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
              <div class="card-body">
                <h4 class="card-title">Loan Application by {{ $user_loan->users->name }}</h4>
                <p class="card-description">

                </p>
                <div class="template-demo">
                  <h4 class="h4 mb-4">Posted on: {{ $user_loan->created_at }}</h4>

                  <p class="font-weight-normal">{{ $user_loan->users->name }} would like to apply for a loan of Ksh {{ $user_loan->loan_value }} which will be paid in a period of {{ $user_loan->duration }} months</p>
                  <p class="font-weight-normal">ID Number: {{ $user_loan->users->id_number }} Phone Number: {{ $user_loan->users->phone_number }}</p>

                  <a href ="{{ route('loan_application.show', ['loan_application' => $user_loan->id]) }}" class="btn btn-success">Make Offer</a>

                  <form action="{{ route('loan_application.destroy', ['loan_application' => $user_loan->id]) }}" method="POST">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                    <button type="submit" class="btn btn-warning">Reject</button>
                  </form>

                   {{-- <a href="/bank/reject/{{ $loan->id }}" class="btn btn-success">Reject</a> --}}

                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  @endcan

@endforeach

@endsection

@section('scripts')
  <script>
    $("#my-alerts").fadeTo(2000, 3000).slideUp(3000, function(){
        $("#my-alerts").slideUp(3000);
      });
  </script>

@endsection

resources/views/bank/logs.blade.php
@extends('layouts.bank_layout')

@section('content')

    <div class="row">
        <div class="col-12 grid-margin">
            <div class="card">
            <div class="card-body">
                <h4 class="card-title">Recently Approved Loans</h4>
                <div class="table-responsive">
                <table class="table" id="example">

                    <!--Table head-->
                    <thead>
                    <tr>
                        <th>
                            Borrower
                        </a>
                        </th>
                        <th>
                            ID Number
                        </th>
                        <th>
                            Phone Number
                        </th>
                        <th>
                            Amount To Be Loaned
                        </th>
                        <th>
                            Duration
                        </th>
                        <th>
                            Offer Status
                        </th>
                        <th>
                            Logged at
                        </th>
                    </tr>
                    </thead>
                    <!--Table head-->

                    <!--Table body-->
                    <tbody>
                    <tr>
                        @foreach($logs as $log)


                        <tr>
                          <td>{{ $log->users->name }}</td>
                          <td>{{ $log->users->id_number }}</td>
                          <td>{{ $log->users->phone_number }}</td>
                          <td>Ksh {{ $log->loan_value }}</td>
                          <td>{{ $log->duration }} months</td>
                          @if($log->bank_verdict->status = "Accepted")
                              <td><label class="badge badge-gradient-success">ACCEPTED</label></td>
                          @elseif ($log->bank_verdict->status = "Rejected")
                              <td><label class="badge badge-gradient-danger">REJECTED</label></td>
                          @else
                              <td><label class="badge badge-gradient-warning">WATING</label></td>
                          @endif
                          <td>{{ $log->created_at }}</td>
                        </tr>


                        @endforeach
                    </tr>
                    </tbody>
                    <!--Table body-->
                </table>

                </div>
            </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')

    <!-- <script src="https://code.jquery.com/jquery-3.3.1.js" type="text/javascript"></script> -->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function() {
            $('#example').DataTable( {
                dom: 'Bfrtip',
                buttons: [
                   'excel', 'pdf', 'print'
                ]
            } );
        } );
    </script>
@endsection

resources/views/bank/package.blade.php
@extends('layouts.bank_layout')

@section('content')
  @foreach ($packages as $package)
    {{-- @can('approve loans') --}}
      <ul>
        <a href="#"><li>{{ $package->title }}</li></a>
        @can ('edit packages')
          <a type="button" class="btn btn-info" href="{{ route('packages.edit', ['packages' => $package->id]) }}">Edit</a>
        @endcan
        <form action="{{ route('bank.accept', [ 'loan_application' => $loan_application->id , 'package' => $package->id ]) }}" method="POST">
            {{ csrf_field() }}
            <button type="submit" class="btn btn-success">Accept</button>
        </form>
      </ul>
    {{-- @endcan --}}
  @endforeach
@endsection